version: '3.1'

services:
  www-westerdao:
    container_name: www-westerdao
    image: www-westerdao
    build: .
    ports:
        - "4000:3000"
    networks:
      - homedock

networks:
  homedock:
    external: true
